FROM ubuntu:20.04
ENV TZ Australia/Sydney

# Install locales and timezone data
RUN apt-get update -qq && \
  apt-get install -qq \
  locales \
  tzdata

# Generate locales
RUN locale-gen $LANG && \
  update-locale LC_ALL=$LC_ALL LANG=$LANG && \
  dpkg-reconfigure --frontend=noninteractive locales

# Set timezone
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && \
  echo $TZ > /etc/timezone

# Install dependencies
RUN apt-get -qq update && \
  apt-get -qq install \
  git \
  gnupg2 \
  software-properties-common \
  systemd \
  tigervnc-scraping-server \
  tigervnc-standalone-server \
  wget \
  x11-apps

# install vbox dependencies
RUN apt-get -qq install psmisc \
  libcurl4 \
  libopus0 \
  libqt5core5a \
  libqt5gui5 \
  libqt5opengl5 \
  libqt5printsupport5 \
  libqt5widgets5 \
  libqt5x11extras5 \
  libsdl1.2debian \
  libvpx6 \
  python2

# install virtualbox
RUN wget -q -O vbox.deb http://download.virtualbox.org/virtualbox/6.1.16/virtualbox-6.1_6.1.16-140961~Ubuntu~eoan_amd64.deb && \
  dpkg -i vbox.deb || apt-get install -qq --fix-broken


# Install novnc
RUN git clone --depth 1 https://github.com/cloud-computer/noVNC.git /opt/noVNC && \
  git clone https://github.com/novnc/websockify /opt/noVNC/utils/websockify


# testing bits
RUN apt-get -qq install nano xdotool kmod

# Create a non-root user for safe operation
RUN useradd \
  --create-home \
  --groups sudo,tty,video \
  vnc

WORKDIR /home/vnc

# Copy windows machine image
COPY windows_machine_logged_in.ova .

RUN apt-get install -y openbox

# Assume non-root user
USER vnc

# copy fullscreen script
COPY fullscreen-always.sh /

# Copy entrypoint
COPY entrypoint.sh /

COPY gdrive-webget.sh /

# Begin entrypoint
ENTRYPOINT /entrypoint-local.sh
